services:
  app:
    build: ./
    container_name: streamlit-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - app-db
    volumes:
      - ./:/app

  app-db:
    image: postgres:15.15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_database:/var/lib/postgresql/data

volumes:
    postgres_database: